//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSkipperApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenSkipperApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;AISDefnCollection xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;AisDefns&gt;
        ///    &lt;AISDefn Description=&quot;Position Report Class A&quot; MessageID=&quot;1&quot;&gt;
        ///      &lt;Fields&gt;
        ///        &lt;UnsignedField Name=&quot;Message Type&quot;&gt;
        ///          &lt;Description&gt;Unsigned integer: 1-3&lt;/Description&gt;
        ///          &lt;BitOffset&gt;0&lt;/BitOffset&gt;
        ///          &lt;BitLength&gt;6&lt;/BitLength&gt;
        ///        &lt;/UnsignedField&gt;
        ///        &lt;UnsignedField Name=&quot;Repeat Indicator&quot;&gt;
        ///          &lt;Descripti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AIS_AISDfn {
            get {
                return ResourceManager.GetString("AIS_AISDfn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ApplicationIcon {
            get {
                object obj = ResourceManager.GetObject("ApplicationIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DeviceClassCollection xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;DeviceClasses&gt;
        ///    &lt;DeviceClass&gt;
        ///      &lt;Name&gt;System Tools&lt;/Name&gt;
        ///      &lt;Code&gt;10&lt;/Code&gt;
        ///      &lt;DeviceFunctions&gt;
        ///        &lt;DeviceFunction&gt;
        ///          &lt;Name&gt;Diagnostic&lt;/Name&gt;
        ///          &lt;Code&gt;130&lt;/Code&gt;
        ///        &lt;/DeviceFunction&gt;
        ///        &lt;DeviceFunction&gt;
        ///          &lt;Name&gt;Bus Traffic Logger&lt;/Name&gt;
        ///          &lt;Code&gt;140&lt;/Code&gt;
        ///        &lt;/DeviceFunction&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassAndFunction_N2kDfn {
            get {
                return ResourceManager.GetString("ClassAndFunction_N2kDfn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Pause {
            get {
                object obj = ResourceManager.GetObject("Image_Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Play {
            get {
                object obj = ResourceManager.GetObject("Image_Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Rewind {
            get {
                object obj = ResourceManager.GetObject("Image_Rewind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ManufacturerCollection xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Manufacturers&gt;
        ///    &lt;Manufacturer&gt;
        ///      &lt;Name&gt;Fw Murphy&lt;/Name&gt;
        ///      &lt;Code&gt;78&lt;/Code&gt;
        ///    &lt;/Manufacturer&gt;
        ///    &lt;Manufacturer&gt;
        ///      &lt;Name&gt;Twin Disc&lt;/Name&gt;
        ///      &lt;Code&gt;80&lt;/Code&gt;
        ///    &lt;/Manufacturer&gt;
        ///    &lt;Manufacturer&gt;
        ///      &lt;Name&gt;Kohler Power Systems&lt;/Name&gt;
        ///      &lt;Code&gt;85&lt;/Code&gt;
        ///    &lt;/Manufacturer&gt;
        ///    &lt;Manufacturer&gt;
        ///      &lt;Name&gt;Hemisphere Gps&lt;/Name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Manufacturers_N2kDfn {
            get {
                return ResourceManager.GetString("Manufacturers_N2kDfn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;N0183DefnCollection xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; Version=&quot;1.0&quot;&gt;
        ///  &lt;Date&gt;8/12/2009 1:19:18 p.m.&lt;/Date&gt;
        ///  &lt;Comment&gt;Test&lt;/Comment&gt;
        ///  &lt;CreatorCode&gt;Jason&lt;/CreatorCode&gt;
        ///  &lt;N0183Defns&gt;
        ///    &lt;N0183Defn Description=&quot;Waypoint Arrival Alarm&quot; Code=&quot;AAM&quot;&gt;
        ///      &lt;Fields&gt;
        ///        &lt;Field Name=&quot;Status, BOOLEAN, A = Arrival circle entered&quot;&gt;
        ///          &lt;Description&gt;A&lt;/Description&gt;
        ///          &lt;SegmentIndex&gt;0&lt;/SegmentIndex&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string N0183Defns_N0183Dfn {
            get {
                return ResourceManager.GetString("N0183Defns_N0183Dfn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ParameterCollection xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Parameters&gt;
        ///    &lt;MultiSourceNumeric&gt;
        ///      &lt;DisplayName&gt;SOG&lt;/DisplayName&gt;
        ///      &lt;InternalName&gt;SOG&lt;/InternalName&gt;
        ///      &lt;KeepHistory&gt;0&lt;/KeepHistory&gt;
        ///      &lt;LockFirstStream&gt;false&lt;/LockFirstStream&gt;
        ///      &lt;LockFirstProtocol&gt;false&lt;/LockFirstProtocol&gt;
        ///      &lt;FormatAs&gt;Custom&lt;/FormatAs&gt;
        ///      &lt;FormatString&gt;0.0 kn&lt;/FormatString&gt;
        ///      &lt;Hooks&gt;
        ///        &lt;MsgHook&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Parameters_N2kParams {
            get {
                return ResourceManager.GetString("Parameters_N2kParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pause1 {
            get {
                object obj = ResourceManager.GetObject("Pause1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;PGNDefnCollection xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; Version=&quot;0.1&quot;&gt;
        ///  &lt;Date&gt;$Date: 2012-03-14 16:30:42 +0100 (wo, 14 mrt 2012) $&lt;/Date&gt;
        ///  &lt;Comment&gt;Test Run&lt;/Comment&gt;
        ///  &lt;CreatorCode&gt;Keversoft NMEA2000 Analyzer&lt;/CreatorCode&gt;
        ///  &lt;PGNDefns&gt;
        ///    &lt;PGNDefn PGN=&quot;59392&quot;&gt;
        ///      &lt;Name&gt;ISO Acknowledgement&lt;/Name&gt;
        ///      &lt;ByteLength&gt;8&lt;/ByteLength&gt;
        ///      &lt;Fields&gt;
        ///        &lt;EnumField Name=&quot;Control&quot;&gt;
        ///          &lt;BitOffset&gt;0&lt;/BitOff [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PGNDefns_N2kDfn {
            get {
                return ResourceManager.GetString("PGNDefns_N2kDfn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Play {
            get {
                object obj = ResourceManager.GetObject("Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rewind {
            get {
                object obj = ResourceManager.GetObject("Rewind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rewind1 {
            get {
                object obj = ResourceManager.GetObject("Rewind1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Step {
            get {
                object obj = ResourceManager.GetObject("Step", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
